name: secret_letter
description: A new Flutter project.

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  get_it: ^4.0.2
  injectable: ^1.0.4
  json_serializable: ^3.2.3
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2

  aes_crypt: ^0.1.1
  flutter_string_encryption: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.8.0
  mobx_codegen: ^1.1.0+2
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true
